#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangkinasih@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+628984880039
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

RED="\033[31m"
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
YELL='\033[0;33m'
BGWHITE='\e[0;100;37m'

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/malisun77/instalasi/main/register"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/+6285176931441"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    exit 0
  fi
}
checking_sc
clear

echo -e ""
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}  ${BGWHITE}            MENU MANAGER SSH OPENVPN            ${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}   ${NC}[${GREEN}01${NC}]${YELL} Create SSH Account${NC}"
echo -e " ${NC}   ${NC}[${GREEN}02${NC}]${YELL} Trial SSH Account${NC}"
echo -e " ${NC}   ${NC}[${GREEN}03${NC}]${YELL} Renew SSH Account${NC}"
echo -e " ${NC}   ${NC}[${GREEN}04${NC}]${YELL} Check login SSH Account${NC}"
echo -e " ${NC}   ${NC}[${GREEN}05${NC}]${YELL} List Member${NC}"
echo -e " ${NC}   ${NC}[${GREEN}06${NC}]${YELL} Delete Acount SSH${NC}"
echo -e " ${NC}   ${NC}[${GREEN}07${NC}]${YELL} Delete User Expired${NC}"
echo -e " ${NC}   ${NC}[${GREEN}08${NC}]${YELL} Auto Killer SSH${NC}"
echo -e " ${NC}   ${NC}[${GREEN}09${NC}]${YELL} Check User MultiLogin${NC}"
echo -e " ${NC}   ${NC}[${GREEN}10${NC}]${YELL} Lock User SSH${NC}"
echo -e " ${NC}   ${NC}[${GREEN}11${NC}]${YELL} Unlock User SSH${NC}"
echo -e " ${NC}   ${NC}[${RED}0X${NC}]${RED} ComeBack Menu${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e ""
read -p "  Select From Options [ 1-11 / 0X ] »» " menu
echo -e ""

case $menu in
1 | 01)
    addssh
    ;;
2 | 02)
    trial
    ;;
3 | 03)
    renewssh
    ;;
4 | 04)
    cekssh
    ;;
5 | 05)
    member
    ;;
6 | 06)
    delssh
    ;;
7 | 07)
    delexp
    ;;
8 | 08)
    autokill
    ;;
9 | 09)
    ceklim
    ;;
10) 
    clear
    lock
   ;;
11)
    clear
    unlock
    ;;
0 | 00 | x | X | 0x | 0X)
    clear
    menu
    ;;        
*)
    m-sshws
    ;;
esac